// Sprint 2 unit tests: the analytics engine, run against the deterministic
// seed fixture, must reproduce the committed golden files exactly. Goldens
// are generated by an INDEPENDENT implementation (scripts/generate-goldens.ts)
// — if these tests fail, the engine is wrong.

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { computeAnalytics } from '@/lib/analytics';
import { generateFixture, SEED_NOW } from '@/lib/seed/fixture';
import type { AnalyticsResult } from '@/lib/analytics/types';

const fixture = generateFixture();
const result: AnalyticsResult = computeAnalytics({
  exercises: fixture.exercises,
  sessions: fixture.workout_sessions,
  sets: fixture.workout_sets,
  goals: fixture.goals,
  now: SEED_NOW,
});

const golden = (name: string): unknown =>
  JSON.parse(
    readFileSync(resolve(__dirname, '../golden', `${name}.golden.json`), 'utf8'),
  );

describe('analytics engine vs goldens', () => {
  it('plateaus match the golden file exactly (trained exercises only)', () => {
    expect(result.plateaus).toEqual(golden('plateaus'));
    // No catalog contamination: exactly the 6 fixture exercises appear.
    expect(Object.keys(result.plateaus).sort()).toEqual(
      fixture.exercises.map((e) => e.id).sort(),
    );
  });

  it('velocity matches the golden file exactly', () => {
    expect(result.velocity).toEqual(golden('velocity'));
  });

  it('anomalies match the golden file exactly', () => {
    expect(result.anomalies).toEqual(golden('anomalies'));
  });

  it('landmarks match the golden file exactly (muscles from working sets only)', () => {
    expect(result.landmarks).toEqual(golden('landmarks'));
    // Neglected muscles come from trained muscles only — never catalog names.
    const trained = new Set(
      fixture.workout_sets
        .filter((s) => (s.set_type ?? 'working') === 'working')
        .map((s) => fixture.exercises.find((e) => e.id === s.exercise_id)?.primary_muscle),
    );
    for (const n of result.landmarks.neglected) {
      expect(trained.has(n.muscle)).toBe(true);
    }
  });

  it('compare matches the golden file exactly', () => {
    expect(result.compare).toEqual(golden('compare'));
  });

  it('forecast matches the golden file exactly', () => {
    expect(result.forecast).toEqual(golden('forecast'));
  });

  it('baselines + weekly volume are sane for the fixture', () => {
    // Bench (id …0001): 136 working sets across 32 sessions.
    const bench = result.baselines.per_exercise[
      'a1000000-0000-4000-8000-000000000001'
    ];
    expect(bench).toBeDefined();
    expect(bench!.top_weight_mean).toBeCloseTo(216.7, 1);
    expect(bench!.top_weight_std).toBeCloseTo(8.33, 1);
    expect(bench!.rpe_mean).toBeCloseTo(8.44, 1);
    // Weekly volume: 16 weeks — 15 complete, current week partial by design.
    expect(result.weekly_volume).toHaveLength(16);
    expect(result.weekly_volume.slice(0, 15).every((w) => w.complete)).toBe(true);
    expect(result.weekly_volume[15].complete).toBe(false);
    // Daily volume totals reconcile with the fixture's working sets.
    const fixtureVolume = fixture.workout_sets
      .filter((s) => (s.set_type ?? 'working') === 'working')
      .reduce((sum, s) => sum + (s.weight ?? 0) * (s.reps ?? 0), 0);
    const engineVolume = result.daily_volume.reduce((sum, d) => sum + d.volume, 0);
    expect(engineVolume).toBeCloseTo(fixtureVolume, 6);
  });
});